import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import ModalProvider from '@/components/provider/modalProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
          <div className='pt-5 px-10'>
            <ModalProvider/>
          {children}
          </div>
        </body>
    </html>
  )
}
